### ISSUE TITLE
Submit to PyPI

### ISSUE THREAD

**Issue by jhurliman** [facebookincubator/bootstrapped#6]
Being able to run `pip install bootstrapped` would be great :).

**Comment by spencebeecher** [comment]
That is a great suggestion! I will start to work this ASAP (perhaps tonight or tomorrow afternoon).

**Comment by jhurliman** [comment]
Friendly nudge to see if this is still on the radar. We're using bootstrapped with Databricks via a custom EGG file right now. Switching to `pip` would simplify things a lot and make it easier to stay up to date with future library updates.

**Comment by spencebeecher** [comment]
Yep i think i can get to this tonight or tomorrow!

**Comment by spencebeecher** [comment]
https://pypi.python.org/pypi/bootstrapped/0.0.1

HUGE props to @graingert for doing this. Thank you!!!
